name: lang_learn
description: A new Flutter project of learning language

version: 1.0.0+1

environment:
  sdk: "^2.12.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  translator: ^0.1.7
  flutter_tts: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
